# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/players_list.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_players(object):
    def setupUi(self, dialog_players):
        dialog_players.setObjectName("dialog_players")
        dialog_players.resize(757, 486)
        dialog_players.setStyleSheet("")
        dialog_players.setModal(True)
        self.gridLayoutWidget = QtWidgets.QWidget(dialog_players)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 744, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.line_search_players = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_search_players.setObjectName("line_search_players")
        self.gridLayout.addWidget(self.line_search_players, 0, 1, 1, 1)
        self.btn_search_players = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_search_players.setAutoFillBackground(False)
        self.btn_search_players.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_search_players.setDefault(False)
        self.btn_search_players.setFlat(False)
        self.btn_search_players.setObjectName("btn_search_players")
        self.gridLayout.addWidget(self.btn_search_players, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_new_player = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_new_player.setAutoFillBackground(False)
        self.btn_new_player.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_new_player.setDefault(False)
        self.btn_new_player.setFlat(False)
        self.btn_new_player.setObjectName("btn_new_player")
        self.verticalLayout.addWidget(self.btn_new_player)
        self.btn_edit_player = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_edit_player.setAutoFillBackground(False)
        self.btn_edit_player.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_edit_player.setFlat(False)
        self.btn_edit_player.setObjectName("btn_edit_player")
        self.verticalLayout.addWidget(self.btn_edit_player)
        self.btn_print_player_card = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_print_player_card.setAutoFillBackground(False)
        self.btn_print_player_card.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_print_player_card.setFlat(False)
        self.btn_print_player_card.setObjectName("btn_print_player_card")
        self.verticalLayout.addWidget(self.btn_print_player_card)
        self.btn_delete_player = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_delete_player.setAutoFillBackground(False)
        self.btn_delete_player.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_delete_player.setFlat(False)
        self.btn_delete_player.setObjectName("btn_delete_player")
        self.verticalLayout.addWidget(self.btn_delete_player)
        self.btn_close_players = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_close_players.setAutoFillBackground(False)
        self.btn_close_players.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_close_players.setFlat(False)
        self.btn_close_players.setObjectName("btn_close_players")
        self.verticalLayout.addWidget(self.btn_close_players)
        self.layout_photo_player = QtWidgets.QVBoxLayout()
        self.layout_photo_player.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_photo_player.setObjectName("layout_photo_player")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_photo_player.addItem(spacerItem)
        self.lbl_photo_player = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_photo_player.setMinimumSize(QtCore.QSize(120, 120))
        self.lbl_photo_player.setMaximumSize(QtCore.QSize(140, 140))
        self.lbl_photo_player.setText("")
        self.lbl_photo_player.setPixmap(QtGui.QPixmap(":/images/asserts/default-user.png"))
        self.lbl_photo_player.setScaledContents(True)
        self.lbl_photo_player.setObjectName("lbl_photo_player")
        self.layout_photo_player.addWidget(self.lbl_photo_player)
        self.verticalLayout.addLayout(self.layout_photo_player)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.table_list_players = QtWidgets.QTableView(self.gridLayoutWidget)
        self.table_list_players.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.table_list_players.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_list_players.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_list_players.setObjectName("table_list_players")
        self.gridLayout.addWidget(self.table_list_players, 1, 1, 1, 1)

        self.retranslateUi(dialog_players)
        QtCore.QMetaObject.connectSlotsByName(dialog_players)

    def retranslateUi(self, dialog_players):
        _translate = QtCore.QCoreApplication.translate
        dialog_players.setWindowTitle(_translate("dialog_players", "Listado de jugadores"))
        self.btn_search_players.setText(_translate("dialog_players", "Buscar"))
        self.btn_new_player.setText(_translate("dialog_players", "Nuevo"))
        self.btn_edit_player.setText(_translate("dialog_players", "Editar"))
        self.btn_print_player_card.setText(_translate("dialog_players", "Imprimir credencial"))
        self.btn_delete_player.setText(_translate("dialog_players", "Eliminar"))
        self.btn_close_players.setText(_translate("dialog_players", "Cerrar"))

from . import resources_rc
