# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/player_edit.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_player_edit(object):
    def setupUi(self, player_edit):
        player_edit.setObjectName("player_edit")
        player_edit.resize(625, 535)
        player_edit.setStyleSheet("background-color: rgb(120, 130, 140);")
        self.gridLayoutWidget = QtWidgets.QWidget(player_edit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 611, 465))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_nombre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_nombre.setObjectName("line_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_nombre)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_apellido = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_apellido.setObjectName("line_apellido")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_apellido)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.date_fecha_nac = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.date_fecha_nac.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_fecha_nac.setCalendarPopup(True)
        self.date_fecha_nac.setObjectName("date_fecha_nac")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_fecha_nac)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.line_lugar_nac = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_lugar_nac.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.line_lugar_nac.setObjectName("line_lugar_nac")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_lugar_nac)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.line_dni = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_dni.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.line_dni.setObjectName("line_dni")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_dni)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.line_domicilio = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_domicilio.setObjectName("line_domicilio")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.line_domicilio)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.date_fecha_incripcion = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.date_fecha_incripcion.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_fecha_incripcion.setCalendarPopup(True)
        self.date_fecha_incripcion.setObjectName("date_fecha_incripcion")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.date_fecha_incripcion)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.pin_division = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pin_division.setObjectName("pin_division")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pin_division)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txt_observaciones = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txt_observaciones.setObjectName("txt_observaciones")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.txt_observaciones)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lbl_fecha_renovacion = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_fecha_renovacion.setObjectName("lbl_fecha_renovacion")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lbl_fecha_renovacion)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lbl_fecha_vigencia = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_fecha_vigencia.setFont(font)
        self.lbl_fecha_vigencia.setStyleSheet("font: 75 14pt \"Arial Sans\";\n"
"color: rgb(85, 0, 0);")
        self.lbl_fecha_vigencia.setObjectName("lbl_fecha_vigencia")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lbl_fecha_vigencia)
        self.line_provincia = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_provincia.setObjectName("line_provincia")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_provincia)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmb_clubes = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_clubes.setObjectName("cmb_clubes")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cmb_clubes)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_photo_player = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_photo_player.setMinimumSize(QtCore.QSize(140, 140))
        self.lbl_photo_player.setMaximumSize(QtCore.QSize(140, 140))
        self.lbl_photo_player.setText("")
        self.lbl_photo_player.setPixmap(QtGui.QPixmap(":/images/asserts/default-user.png"))
        self.lbl_photo_player.setScaledContents(True)
        self.lbl_photo_player.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_photo_player.setObjectName("lbl_photo_player")
        self.verticalLayout.addWidget(self.lbl_photo_player)
        self.btn_change_photo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_change_photo.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_change_photo.setObjectName("btn_change_photo")
        self.verticalLayout.addWidget(self.btn_change_photo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(player_edit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 480, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_print_card = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_print_card.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_print_card.setObjectName("btn_print_card")
        self.horizontalLayout.addWidget(self.btn_print_card)
        self.btn_save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_save.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cancel.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.retranslateUi(player_edit)
        QtCore.QMetaObject.connectSlotsByName(player_edit)
        player_edit.setTabOrder(self.line_nombre, self.line_apellido)
        player_edit.setTabOrder(self.line_apellido, self.date_fecha_nac)
        player_edit.setTabOrder(self.date_fecha_nac, self.line_lugar_nac)
        player_edit.setTabOrder(self.line_lugar_nac, self.line_provincia)
        player_edit.setTabOrder(self.line_provincia, self.line_dni)
        player_edit.setTabOrder(self.line_dni, self.line_domicilio)
        player_edit.setTabOrder(self.line_domicilio, self.date_fecha_incripcion)
        player_edit.setTabOrder(self.date_fecha_incripcion, self.pin_division)
        player_edit.setTabOrder(self.pin_division, self.cmb_clubes)
        player_edit.setTabOrder(self.cmb_clubes, self.txt_observaciones)
        player_edit.setTabOrder(self.txt_observaciones, self.btn_change_photo)
        player_edit.setTabOrder(self.btn_change_photo, self.btn_save)
        player_edit.setTabOrder(self.btn_save, self.btn_cancel)
        player_edit.setTabOrder(self.btn_cancel, self.btn_print_card)

    def retranslateUi(self, player_edit):
        _translate = QtCore.QCoreApplication.translate
        player_edit.setWindowTitle(_translate("player_edit", "Datos del jugador"))
        self.label_2.setText(_translate("player_edit", "Nombre:"))
        self.label_3.setText(_translate("player_edit", "Apellido:"))
        self.label_4.setText(_translate("player_edit", "Fecha Nacimiento:"))
        self.date_fecha_nac.setDisplayFormat(_translate("player_edit", "dd/MM/yyyy"))
        self.label_5.setText(_translate("player_edit", "Lugar Nacimiento:"))
        self.label_6.setText(_translate("player_edit", "Provincia:"))
        self.label_7.setText(_translate("player_edit", "DNI:"))
        self.label_8.setText(_translate("player_edit", "Domicilio:"))
        self.label_9.setText(_translate("player_edit", "Fecha Inscripción:"))
        self.date_fecha_incripcion.setDisplayFormat(_translate("player_edit", "dd/MM/yyyy"))
        self.label_10.setText(_translate("player_edit", "División:"))
        self.label_11.setText(_translate("player_edit", "Observaciones:"))
        self.label_12.setText(_translate("player_edit", "Fecha de actualización:"))
        self.lbl_fecha_renovacion.setText(_translate("player_edit", "-"))
        self.label_14.setText(_translate("player_edit", "Vigencia hasta:"))
        self.lbl_fecha_vigencia.setText(_translate("player_edit", "-"))
        self.label.setText(_translate("player_edit", "Club:"))
        self.btn_change_photo.setText(_translate("player_edit", "Cambiar foto..."))
        self.btn_print_card.setText(_translate("player_edit", "Imprimir credencial"))
        self.btn_save.setText(_translate("player_edit", "Guardar"))
        self.btn_cancel.setText(_translate("player_edit", "Cancelar"))

import resources_rc
